version: 0.0.{build}
image: Visual Studio 2019

environment:
  matrix:
  - solution_name: LocStatsBackend\LocStatsBackend.sln
    is_mobile: false

  - solution_name: LocStatsMobile\MobileApp\MobileApp.sln
    is_mobile: true


install:
  - ps: $env:ANDROID_HOME="$env:APPVEYOR_BUILD_FOLDER\android"
  - cmd: if %is_mobile% equ true echo y | "C:\Program Files (x86)\Android\android-sdk\tools\bin\sdkmanager.bat" "platform-tools" "platforms;android-30"

before_build:
  - ps: Write-Host $env:is_mobile
  - ps: nuget restore $env:solution_name -Verbosity quiet
  - ps: |
      if ($env:is_mobile -eq $true)
      {
        $file = 'LocStatsMobile\MobileApp\Managers\ConnectionManager.cs'
        $regex = '(?<=private const string URL = ")[^"]*'
        (Get-Content $file) -replace $regex, 'https://locstats.azurewebsites.net/' | Set-Content $file -Encoding UTF8
        Write-Host (Get-Content $file | Select-String -Pattern $regex)
      }

build_script:
  - cmd: if %is_mobile% neq true msbuild /p:Configuration=Release %solution_name%
  - cmd: if %is_mobile% equ true msbuild /t:PackageForAndroid /p:Configuration=Release %solution_name%

test_script:
  - cmd: if %is_mobile% neq true dotnet test %solution_name%

artifacts:
  - path: '**\*.apk'
    name: LocStatsApk