version: 0.0.{build}
image: Visual Studio 2019
environment:
  matrix:
  - solution_name: LocStatsBackend\LocStatsBackend.sln
  - solution_name: LocStatsMobile\MobileApp\MobileApp.sln
before_build:
  - ps: nuget restore $env:solution_name
build_script:
  - msbuild %solution_name%
test_script:
  - dotnet test %solution_name%