version: 0.0.{build}
image: Visual Studio 2019

environment:
  ANDROID_HOME: "C:\\android"
  matrix:
  - solution_name: LocStatsBackend\LocStatsBackend.sln
  - solution_name: LocStatsMobile\MobileApp\MobileApp.sln

init:
  - mkdir "%ANDROID_HOME%
  - appveyor DownloadFile "https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip"
  - 7z x "sdk-tools-windows-4333796" -o$env:ANDROID_HOME > nul

install:
  - echo y | $env:ANDROID_HOME\tools\bin\sdkmanager.bat --licenses

before_build:
  - ps: nuget restore $env:solution_name > nul
build_script:
  - msbuild %solution_name%
test_script:
  - dotnet test %solution_name%