name: LocStats MobileApp

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore LocStatsMobile/MobileApp/MobileApp.sln

    - name: Build
      run: msbuild LocStatsMobile/MobileApp/MobileApp.sln
      
    - name: Test
      run: dotnet test LocStatsMobile/MobileApp/MobileApp.sln
